language: node_js
node_js:
  - "8.9.0"
git:
  submodules:
    false
before_install:
  - echo -e "machine github.com\n  login $PXT_LOGIN\n  password $PXT_PW" >~/.netrc
  - git submodule update --init --recursive
script:
  - "node node_modules/pxt-core/built/pxt.js travis"
sudo: false
cache:
  directories:
    - node_modules

